@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {

}


class Administrator {

}

class Courier {
  -String idPharmacy
}

class ElectricScooter {
  -Integer uniqueNumber
  -Integer batteryCapacity

}

class Pharmacy {
  -String id
  -String name
}

class PharmacyPark {
  -Integer capacity

}

class RegisteredUser {
  -String name
  -String email
  -String homeAddress
  -String gpsLocation
  -String creditCardNumber
  -String validityDate
  -Integer CCV
}

class Product {
  -String id
  -String name
}

class Order {
    -List products
    -Integer uniqueNumber
    -Integer weight
    -String state
}

class Delivery {
    -Integer distance
}


Platform "1" -- "*" Administrator : has >

Platform "1" -- "*" RegisteredUser : has >


Platform "1" -- "1" Pharmacy : has >

Administrator "1" -- "1" Pharmacy : creates >

RegisteredUser "1" -- "1" Pharmacy : registers on >

RegisteredUser "1" -- "1" Order : does >

Order "1" -- "1" Delivery : generates >

Pharmacy "1" -- "1" PharmacyPark : has >

Pharmacy "1" -- "*" Courier : has >

Pharmacy "1" -- "*" Product : has >

Courier "1" -- "1" ElectricScooter : has >

Pharmacy "1" -- "*" ElectricScooter : has >

Delivery "1" -- "1" Courier : has >
Delivery "1" -- "1" Courier : has >
@enduml
